###############################
# chrisnft/sandbox/client
# Warning: This is experimental.
###############################
version: '3.9'

services:
  # Dev backend
  client:
    image: client
    container_name: client
    build:
      context: .
      dockerfile: ./Dockerfile 
    ports:
      - "8545"
    stdin_open: true
    tty: true
